api_version = "2026-07"

[[extensions]]
type = "ui_extension"
# Change the merchant-facing name of the extension in locales/en.default.json
name = "t:name"
uid = "6ecc6dbb-a218-4da1-52a8-8e731ac98900fc0f397d"
handle = "hotwax-cycle-count"
description = "Count inventory locally and synchronize with HotWax OMS."

# module: file that contains your extension’s source code
# target: location where your extension appears in POS
[[extensions.targeting]]
module = "./src/Tile.jsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/Modal.jsx"
target = "pos.home.modal.render"

[[extensions.targeting]]
module = "./src/Background.js"
target = "pos.app.ready.data"

[[extensions.targeting]]
module = "./src/ProductAction.jsx"
target = "pos.product-details.action.menu-item.render"

[[extensions.targeting]]
module = "./src/Modal.jsx"
target = "pos.product-details.action.render"

[extensions.supported_features]
runs_offline = true
